on: push
name: pypi
jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  pypi:
    name: Pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install wheel
      - name: Build package
        run: python setup.py sdist bdist_wheel
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with: 
          password: ${{ secrets.pypi_password }}
          user: __token__
